#!/bin/sh

function help () {
 echo '';
}

# Setup Config
read -p 'Enter your MySQL username (normally root): ' mysql_username;
echo ''
#read -s -p 'Enter your MySQL password: ' mysql_password;
#echo ''
#echo ''
read -p 'Enter your MySQL database name (normally creative-store): ' mysql_database;
echo ''
read -p 'Enter the path to your WordPress site: eg "localhost/creative-store" ' url_wordpress;

# Install NPM dependencies
echo ''
echo 'Installing NPM dependencies...'
npm install

# Copy config files
echo ''
echo 'Installing config files...'
cp ./_scripts/local-config-sample.php ./local-config.php
cp ./_scripts/wp-config-sample.php ./wp-config.php

echo ''
echo 'Remember to add in your local MySQL database name, username'
echo 'and password to the local-config.php file'

# Install the MySQL database
echo ''
echo 'Creating the MySQL database...'
mysql -u $mysql_username -p -e "create database "${mysql_database}";"
echo ''
echo 'Import the Creative Store MySQL database...'
mysql -u $mysql_username -p ${mysql_database} < ~/Dropbox/creative-store/creative-store_dummy-data.sql

# Update WordPress options for local site
echo ''
echo 'Updating the Creative Store MySQL database...'
# Update WordPress Options
# TODO: SQL to update options
# Update Post urls
mysql -u $mysql_username -p $mysql_database -e 'UPDATE wp_posts SET guid = REPLACE( guid, "10.152.22.242/creative-store", "'${url_wordpress}'" );'

# Install our git pre-commit hook
echo ''
echo 'Installing pre-commit hook...'
ln -s ../../_scripts/pre-commit .git/hooks/pre-commit

echo ''
echo 'Applying ownership and permissions...'
sudo chown -R _www ./
sudo chmod -R g+w ./

#  Run grunt
echo ''
echo 'Run Grunt...'
grunt
