#!/bin/sh
#
# Setup the vagrant environment

# Setup PHP
echo "Setup PHP..."
phpenv local 5.5
# Install PHP dependancies
php -n /home/rof/bin/composer config -g github-oauth.github.com $GITHUB_ACCESS
php -n /home/rof/bin/composer install --no-interaction  --prefer-dist

# Setup NodeJS
echo "Setup NodeJS..."
nvm install 4.6
# Install dependancies for running your tests or other tasks
npm install -g grunt-cli
npm install -g bower

echo "Setup WordPress Theme..."
cd ~/clone/html/app/themes/creative-store/
./_scripts/provision-ci
echo "WordPress Theme Built"
cd ~/clone/
