#!/bin/sh
#
# Provision Theme


# Setup Theme
echo "Installing dependancies..."
php -n /home/rof/bin/composer config -g github-oauth.github.com $GITHUB_ACCESS
php -n /home/rof/bin/composer install --no-interaction  --prefer-dist

npm install
grunt
